log:
  level: error #日志级别。可选 "debug" "info" "warn" "error"。默认 "info"
  file: "/var/log/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"

include: []

plugins:
 ################ DNS #################
 # 测试pipeline mosdns probe pipeline tls://1.12.12.12	支持
 # 测试pipeline mosdns probe pipeline tls://8.8.8.8	支持
   # google doh dot h3
  - tag: google
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::6464"
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::0064"
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8844"
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8888"
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"

        - addr: "tls://dns.google"
          dial_addr: "2001:4860:4860::8844"
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "2001:4860:4860::8888"
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.4.4"
          enable_pipeline: true

     # h3
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8844"
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8888"
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          enable_http3: true

  # cloudflare doh dot h3
  - tag: cloudflare
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "2606:4700:4700::1001"
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.0.0.1"
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "2606:4700:4700::1111"
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1"

        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "2606:4700:4700::1001"
          enable_pipeline: true # TCP/DoT 启用 RFC 7766 新的 query pipelining 连接复用模式
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "1.0.0.1"
          enable_pipeline: true
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "2606:4700:4700::1111"
          enable_pipeline: true
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "1.1.1.1"
          enable_pipeline: true

        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "2606:4700:4700::1001"
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.0.0.1"
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "2606:4700:4700::1111"
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1"
          enable_http3: true

  # ali doh dot h3
  - tag: ali
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "2400:3200:baba::1"
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "2400:3200::1"
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.6.6.6"

        - addr: "tls://dns.alidns.com"
          dial_addr: "2400:3200:baba::1"
          enable_pipeline: true
        - addr: "tls://dns.alidns.com"
          dial_addr: "223.5.5.5"
          enable_pipeline: true
        - addr: "tls://dns.alidns.com"
          dial_addr: "2400:3200::1"
          enable_pipeline: true
        - addr: "tls://dns.alidns.com"
          dial_addr: "223.6.6.6"
          enable_pipeline: true

        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "2400:3200:baba::1"
          enable_http3: true
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
          enable_http3: true
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "2400:3200::1"
          enable_http3: true
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.6.6.6"
          enable_http3: true

  # dnspod doh dot
  - tag: dnspod
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
        - addr: "https://doh.pub/dns-query"
          dial_addr: "120.53.53.53"

        - addr: "tls://dot.pub"
          dial_addr: "1.12.12.12"
          enable_pipeline: true
        - addr: "tls://dot.pub"
          dial_addr: "120.53.53.53"
          enable_pipeline: true

  # local_dns  转发至本地服务器
  - tag: smartdns
    type: forward
    args:
      upstreams:
      #smartdns_local_port *** modify port sign not move
        - addr: "127.0.0.1:6053"

  # local_smartdns_oversea  转发至国外服务器
  - tag: smartdns_oversea
    type: forward
    args:
      upstreams:
      #smartdns_oversea_port *** modify port sign not move
        - addr: "127.0.0.1:8653"

  # 自定义hosts
  - tag: localhosts
    type: hosts
    args:
#     entries:
#        - "domain:R3P 192.168.1.119"
#        - "domain:MI3K 192.168.1.120"
     files:
        - "/etc/mosdns/rule/hosts.txt"

  - tag: blocklist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/blocklist.txt"

  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/local-ptr.txt"

  # ddns & vpnsite whitelist域名国内可访问
  - tag: can_cn_site
    type: domain_set
    args:
      files:
#        - "/etc/sysmonitor/rule/apple-cn.txt"
#        - "/etc/sysmonitor/rule/google-cn.txt"
        - "/etc/sysmonitor/rule/vpnsite.txt"
        - "/etc/mosdns/rule/ddnslist.txt"        
        - "/etc/mosdns/rule/whitelist.txt"

# Clourflare IP
  - tag: geoip_cfip
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rule/cloudflare-cidr.txt"

 # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"

 # 国内 IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt" 

# ipv4 domain
  - tag: ipv4_domain
    type: domain_set
    args:
      files:
        - "/etc/sysmonitor/rule/ipv4.txt"

  - tag: geosite_gfw
    type: domain_set
    args:
      files:
        - "/usr/share/passwall/rules/gfwlist"
        - "/etc/mosdns/rule/greylist.txt"

  # 重定向列表
  - tag: redirect_list
    type: domain_set
    args:
      files:
       - "/etc/mosdns/rule/redirect.txt"

  ################ 序列 #################

# 修改 TTL
  - tag: modify_ttl
    type: "sequence"
    args:
      - exec: ttl 5-10

  - tag: modify_black_ttl
    type: "sequence"
    args:
      - exec: ttl 600-3600
  
  - tag: smartdns_nocn
    type: "fallback"
    args:
      primary: smartdns_oversea # 主dns
      secondary: google # 备用dns
      threshold: 300 # 无响应切换 毫秒
      always_standby: true # 副可执行插件始终待命
  
  - tag: dns_nocn
    type: "fallback"
    args:
      primary: smartdns_oversea # 主dns
      secondary: cloudflare # 备用dns
      threshold: 300 # 无响应切换 毫秒
      always_standby: true # 副可执行插件始终待命

  # dns-smartdns_cn 序列
  - tag: smartdns_cn
    type: "fallback"
    args:
      primary: smartdns # 主dns
      secondary: dnspod # 备用dns
      threshold: 15
      always_standby: true # 副可执行插件始终待命

  # dns-cn 序列
  - tag: dns_cn
    type: "fallback"
    args:
      primary: smartdns # 主dns
      secondary: ali # 备用dns
      threshold: 15
      always_standby: true # 副可执行插件始终待命

  # 缓存
#  - tag: lazy_cache
#    type: cache
#    args:
#      size: 5120
#      lazy_cache_ttl: 86400

#      dump_file: "/etc/mosdns/cache.dump"
#      dump_interval: 600

  # 国内解析
  # 返回非国内 ip 则 drop_resp
  - tag: local_sequence
    type: sequence
    args:
      - exec: $smartdns_cn
#      - matches: "!resp_ip $geoip_cn" # 响应 非cn ip
#        exec: drop_resp # 丢弃

  # 国外解析
  # 返回非国外 ip 则 drop_resp
  - tag: remote_sequence
    type: sequence
    args:
      - exec: prefer_ipv4    
      - exec: $smartdns_nocn
#      - matches: "resp_ip $geoip_cn" # 响应为 cn ip    
#        exec: drop_resp # 丢弃

 # ipv4_domain 解析
  - tag: ipv4_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $smartdns_nocn

 # 查询国内域名
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $local_sequence

  # 查询国外ipv4域名
  - tag: query_is_no_local_ipv4_domain
    type: sequence
    args:
      - matches: qname $ipv4_domain
        exec: $ipv4_sequence

  # 查询国外域名
  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $remote_sequence

  # 查询国外GFW域名
  - tag: query_is_gfw_domain
    type: sequence
    args:
      - matches: qname $geosite_gfw
#        exec: $remote_sequence
        exec: $smartdns_nocn

  # ddns & vpnsite whitelist域名国内可访问
  - tag: query_is_can_cn_domain
    type: sequence
    args:
#      - matches: qtype 255 # TYPE 255 类型|DNS服务器拓展支持
#        exec: $smartdns_cn
      - matches: qname $can_cn_site
        exec: $smartdns_cn
 
  - tag: query_is_reject_domain
    type: sequence
    args:
      - exec: jump modify_black_ttl
      - matches: qname $blocklist
        exec: reject
#      - matches: 
#        - qtype 12
#        - "qname $local_ptr"
#        exec: reject 3
#      - matches: qtype 65
#        exec: reject 3
      - matches: "qname keyword::" # 无效域名
        exec: reject 3

  # main_sequence 结果处理
  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - exec: jump modify_ttl
      - matches: has_resp
        exec: accept

  # fallback sequence
  - tag: fallback
    type: sequence
    args:
      - exec: $dns_nocn
      - exec: jump has_resp_sequence
      - exec: $dns_cn
      - exec: jump has_resp_sequence

# 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:

      - exec: $localhosts
      - exec: jump has_resp_sequence

      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence

      - exec: $query_is_can_cn_domain # ddns & vpnsite whitelist域名国内可访问
      - exec: jump has_resp_sequence

#      - exec: $query_is_no_local_ipv4_domain  #国外ipv4域名
#      - exec: jump has_resp_sequence

      - exec: $query_is_gfw_domain #  GFW域名
      - exec: jump has_resp_sequence

      - exec: $query_is_no_local_domain  #国外域名
      - exec: jump has_resp_sequence

      - exec: $query_is_local_domain  #国内域名处理 放在国外前，ai将不能工作(出现所在国不支持)
      - exec: jump has_resp_sequence

      - exec: jump fallback


 # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      #mosdns_udp_port *** modify port sign not move
      listen: ":53"

  # 启动 tcp 服务器。
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      #mosdns_tcp_port *** modify port sign not move
      listen: ":53"